# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='travelers',
            field=models.ManyToManyField(related_name='users_who_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
