# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
